increment 14
DrGermanius/Shortener pull request #4
Opened 2022-01-15 18:08 UTC by DrGermanius

2022-01-17 05:18 UTC, Perederey requested changes
В целом отличный код!

Но есть несколько моментов.
1) В последнем задании BatchDelete нужно реализовать с помощью каналов. понимаю, что и на уровне базы данных это возможно сделать, но наша задача учебная и мы хотим закрепить тему с каналами. (плюс я привел пример с 3 млн. записями, где запрос работать не будет)
2) Нигде не используется context.WithTimeout() и соответственно  нигде нет обработки <-ctx.Done(). Надо эту штуку также внедрить.

2022-01-17 05:18 UTC, Perederey commented on cmd/shortener/main.go
> +	zapl, err := zap.NewProduction()
давай немного усложним тебе задание, так как у тебя хорошо получается

А сможешь сделать разные уровни логера в зависимости от текущей env? И например для local записывать лог и в консоль и в файл одновременно?

Или же попробуй еще ради эксперимента zerolog (сейчас считается более продвинутым) и реализуй через него на local красивый вывод в консольку

2022-01-17 05:18 UTC, Perederey commented on internal/app/handlers/handlers.go
> +func NewHandlers(store store.LinksStorager, logger *zap.SugaredLogger) *Handlers {
а почему решил `Handlers` передавать указателем?
Store у тебя уже и так по-факту указатель, блоггер внутри тоже указатель. `Handlers` может быть и без указателя.

2022-01-17 05:18 UTC, Perederey commented on internal/app/handlers/handlers.go
> +	defer req.Body.Close()
defer лучше сразу после ioutil.ReadAll() указать

2022-01-17 05:18 UTC, Perederey commented on internal/app/handlers/handlers.go
> +	ctx := context.Background()
лучше возьми ctx из реквеста
`req.Context()`

2022-01-17 05:18 UTC, Perederey commented on internal/app/handlers/handlers_test.go
> +				code: http.StatusAccepted,
может быть в тесте проверять еще заголовки и body?

2022-01-17 05:18 UTC, Perederey commented on internal/app/handlers/handlers.go
> +	_, err = w.Write([]byte{})
в API обычно возвращают jobID, можешь это реализовать (вроде бы тесты сломаться не должны) (как доп задание)

2022-01-17 05:18 UTC, Perederey commented on internal/store/database/database.go
> +	_, err := d.conn.Exec(ctx, "UPDATE links SET is_deleted = true WHERE user_id = $1 AND short_link = any($2)", uid, links)
это удаление на уровне базы данных (отличный вариант),но  в задании просят использовать именно удаление на уровне приложения (представь, что у тебя записей на удаление 3 млн, тогда тебе нужно делить все на чанки), и с помощью удаления через базу твой запрос просто не применяет MySQL сервер.

2022-01-17 05:18 UTC, Perederey commented on internal/store/memory/memory.go
> +func (l *LinkMemoryStore) BatchDelete(ctx context.Context, uid string, links []string) error {
можно вот так еще и не нужно делать анонимное присваинвание

```go
func (l *LinkMemoryStore) BatchDelete(_ context.Context, uid string, links []string) error
```

2022-01-17 05:18 UTC, Perederey commented on internal/store/memory/memory.go
> +			(*l)[link] = updatedLink
а почему бы не сделать все методы без указателя?

func (l LinkMemoryStory)

2022-01-17 05:18 UTC, Perederey commented on internal/store/store.go
> +	case "":
а куда делся File? он должен быть или опцией для InMemory, либо отдельно

2022-01-17 05:37 UTC, DrGermanius commented on internal/app/handlers/handlers.go
> +	ctx := context.Background()
первоначально так и делал, но оказалось, что req.Context закрываетя сразу после отправки ответа
// For incoming server requests, the context is canceled when the
// client's connection closes, the request is canceled (with HTTP/2),
// or when the ServeHTTP method returns.

2022-01-22 19:21 UTC, DrGermanius commented on internal/store/store.go
> +	case "":
File всегда по дефолту создается для InMemory. Либо по пути, который в env или параметрах запуска в консоли, либо по дефолтному пути

2022-01-22 19:24 UTC, DrGermanius commented on internal/app/handlers/handlers_test.go
> +				code: http.StatusAccepted,
Все заголовки и body проверяются в первых тестах, а этот тестирует чисто функционал удаления. Думаю не стоит перегружать его логику

2022-01-24 19:30 UTC, Perederey approved these changes
Да, все отлично!
PR принимаю, единственное, я оставил комментарий по-поводу worker, надо еще раз переделать (сорри ;) )

2022-01-24 19:30 UTC, Perederey commented on internal/app/handlers/handlers.go
> +	go wp.Run()
я видимо тебе не совсем верно объяснил сам воркер можно запускаться не в handler, а например в main.go (вместе с сервером)

а здесь ты передаешь только сообщения в канал (который ты при запуске воркера вернешь и вставишь сюда ;) )

2022-01-29 08:50 UTC, merged